steps:

- id: Test
  name: golang
  args: ['go', 'test', '-v']

- id: Build
  name: golang
  args: ['go', 'build', '.']

- id: Build Image
  name: 'docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/quickstart-image', '.' ]